#!/bin/bash

# Install Apache Web Server
sudo yum install -y httpd
sudo systemctl enable httpd
sudo systemctl start httpd

# Install MariaDB (MySQL)
sudo yum install -y mariadb105-server
sudo systemctl enable mariadb
sudo systemctl start mariadb

# Setting up MySQL Database
MYSQL_ROOT_PASSWORD="rootpassword"
DB_NAME="wordpress"
DB_USER="wp-user"
DB_PASS="wordpress"

# Set MySQL root password and create WordPress database
sudo mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED BY '$MYSQL_ROOT_PASSWORD'; FLUSH PRIVILEGES;"
sudo systemctl restart mariadb

# Create WordPress database and user
sudo mysql -u root -p"$MYSQL_ROOT_PASSWORD" <<EOF
CREATE DATABASE $DB_NAME;
CREATE USER '$DB_USER'@'localhost' IDENTIFIED BY '$DB_PASS';
GRANT ALL PRIVILEGES ON $DB_NAME.* TO '$DB_USER'@'localhost';
FLUSH PRIVILEGES;
EOF

echo "MYSQL Database and User Created"

# Install PHP 
sudo dnf install -y php php-cli php-mysqlnd php-json php-opcache php-mbstring php-xml php-gd

# Download and Setup WordPress
cd /var/www/html
sudo rm -rf wordpress
sudo wget https://wordpress.org/latest.tar.gz
sudo tar -xzf latest.tar.gz
sudo rm -f latest.tar.gz
sudo chown -R apache:apache /var/www/html/wordpress
sudo chmod -R 755 /var/www/html/wordpress

# Configure Apache for WordPress
sudo tee /etc/httpd/conf.d/wordpress.conf > /dev/null <<EOF
<VirtualHost *:80>
    ServerAdmin webmaster@localhost
    DocumentRoot /var/www/html/wordpress
    <Directory "/var/www/html/wordpress">
        AllowOverride All
        Require all granted
    </Directory>
    ErrorLog /var/log/httpd/wordpress_error.log
    CustomLog /var/log/httpd/wordpress_access.log combined
</VirtualHost>
EOF

sudo systemctl restart httpd

# Configure WordPress settings
cd /var/www/html/wordpress
sudo cp wp-config-sample.php wp-config.php
sudo sed -i "s/database_name_here/$DB_NAME/" wp-config.php
sudo sed -i "s/username_here/$DB_USER/" wp-config.php
sudo sed -i "s/password_here/$DB_PASS/" wp-config.php

sudo systemctl restart httpd


PUBLIC_IP=$(curl -s  http://169.254.169.254/latest/meta-data/public-ipv4)
echo "🚀 WORDPRESS installation completed! Visit: http://$PUBLIC_IP"
